name: ISW2 Testing OpenJPA Ba-Dua
on:
  push:
    branches:
      - isw2
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.372
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Clone and build Ba-Dua repository
        run: |
          git clone https://github.com/saeg/ba-dua
          cd ba-dua
          git checkout d2401f0
          mvn clean install
          cd ..
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean verify -P Ba-Dua

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: BaDuaReport
          path: openjpa-kernel/target/badua.xml
          if-no-files-found: error